In [1]:
import numpy as np

In [3]:
print '使用普通一维数组生成Numpy一维数组'
data = [6, 7.5, 8, 0, 1]
arr =  np.array(data)
print arr
print '打印元素类型'
print arr.dtype

使用普通一维数组生成Numpy一维数组
[ 6.   7.5  8.   0.   1. ]
打印元素类型
float64


In [4]:
print '使用普通二维数组生成NumPy二维数组'
data= [[1, 2, 3, 4],[5, 6, 7, 8]]
arr = np.array(data)
print arr
print '维度'
print arr.shape

使用普通二维数组生成NumPy二维数组
[[1 2 3 4]
 [5 6 7 8]]
维度
(2L, 4L)


In [6]:
print '使用zeros/empty'
print np.zeros(10) #10个0
print np.zeros((3, 6)) #3*6 全0数组
print np.empty((2,3,2)) #2*3*2数组 未初始化

使用zeros/empty
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
[[[ -2.85997747e+174   1.14578545e+243]
  [  1.13224202e+277   2.43813713e-152]
  [  1.09936966e+248   1.47999830e-076]]

 [[  8.82069558e+199   6.79000872e+180]
  [  9.64755386e-048   1.65312950e-153]
  [ -2.95588118e+191   6.17139036e-038]]]


In [8]:
print '使用arrange生成连续元素'
print np.arange(15)

使用arrange生成连续元素
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [15]:
print '使用ones'
a = np.ones((2,10))
print a
print np.ones_like(a)

使用ones
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


In [19]:
print np.eye(4)
print np.identity(5)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


In [32]:
print 'astype类型转换'
b= np.arange(15).astype('string')
print b
print b.astype('float32')
print b.dtype
print b.astype('float64')

astype类型转换
['0' '1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12' '13' '14']
[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.]
|S11
[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.]


In [31]:
print '指定dtype创建ndarray'
print np.ones(15,dtype='string')

指定dtype创建ndarray
['1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1']
