In [1]:
import numpy as np

In [3]:
print '使用普通一维数组生成Numpy一维数组'
data = [6, 7.5, 8, 0, 1]
arr =  np.array(data)
print arr
print '打印元素类型'
print arr.dtype

In [3]:
print '使用普通二维数组生成NumPy二维数组'
data= [[1, 2, 3, 4],[5, 6, 7, 8]]
arr = np.array(data)
print arr
print '维度'
print arr.shape

使用普通二维数组生成NumPy二维数组
[[1 2 3 4]
 [5 6 7 8]]
维度
(2L, 4L)


In [4]:
print '使用zeros/empty'
print np.zeros(10) #10个0
print np.zeros((3, 6)) #3*6 全0数组
print np.empty((2,3,2)) #2*3*2数组 未初始化

使用zeros/empty
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
[[[  0.00000000e+000   6.36598737e-314]
  [  0.00000000e+000   1.27319747e-313]
  [  1.27319747e-313   1.27319747e-313]]

 [[  2.96439388e-323   1.90979621e-313]
  [  0.00000000e+000   2.75859453e-313]
  [  6.91691904e-323   3.60739284e-313]]]


In [5]:
print '使用arrange生成连续元素'
print np.arange(15)

使用arrange生成连续元素
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [6]:
print '使用ones'
a = np.ones((2,10))
print a
print np.ones_like(a)

使用ones
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


In [7]:
print np.eye(4)
print np.identity(6)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[[ 1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.]]


In [8]:
print 'astype类型转换'
b= np.arange(15).astype('string')
print b
print b.astype('float32')
print b.dtype
print b.astype('float64')

astype类型转换
['0' '1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12' '13' '14']
[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.]
|S11
[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.]


In [9]:
print '指定dtype创建ndarray'
print np.ones(15,dtype='string')

指定dtype创建ndarray
['1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1']
