In [16]:
import numpy as np
from numpy import asarray

In [17]:
#通过索引访问二维数组某一行或某个元素
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print arr[2]
print arr[0][2]
print arr[0, 2] # 普通Python数组不能用。

[7 8 9]
3
3


In [18]:
# 对更高维数组的访问和操作
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10,11,12]]])
print arr[0]
print arr[1, 0]
old_values = arr[0].copy() #复制arr[0]
arr[0] = 42
print arr
print 
arr[0] = old_values
print arr

[[1 2 3]
 [4 5 6]]
[7 8 9]
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [22]:
# 附asarray 拷贝为ndarray的使用方法
a = [1, 2, 3]
b = asarray(a)
print b
b.dtype

[1 2 3]


dtype('int32')

In [32]:
print '使用切片访问和操作数组'
arr = np.arange(10)+1
print arr
print arr [1:6]
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print arr[:2]
print arr[:2, 1:]
print arr[:, :1]
arr[:2, 1:]=0
print arr

使用切片访问和操作数组
[ 1  2  3  4  5  6  7  8  9 10]
[2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]
[[1]
 [4]
 [7]]
[[1 0 0]
 [4 0 0]
 [7 8 9]]
