In [24]:
import numpy as np
import numpy.random as np_random

In [25]:
print '使用布尔数组作为索引'
name_arr = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
rnd_arr = np_random.randn(7, 4) # random 7*4 array
print rnd_arr
print name_arr == 'Bob'
print rnd_arr[name_arr == 'Bob']
print rnd_arr[name_arr == 'Bob', :2]

使用布尔数组作为索引
[[-1.42800631 -2.62500425 -1.52057421 -1.3482058 ]
 [ 0.4409493   1.48540013  0.40731781  0.16606016]
 [ 0.84783595 -2.15533993  1.50628519 -0.31510995]
 [-1.59846491 -1.47390465 -0.13706371 -2.51937338]
 [ 0.15842983 -0.11273919  0.06812044 -0.24180305]
 [-1.73153848  0.32802232 -0.28211856 -0.22661218]
 [-0.00328644 -0.15188049  0.92744076 -1.04438799]]
[ True False False  True False False False]
[[-1.42800631 -2.62500425 -1.52057421 -1.3482058 ]
 [-1.59846491 -1.47390465 -0.13706371 -2.51937338]]
[[-1.42800631 -2.62500425]
 [-1.59846491 -1.47390465]]


In [26]:
print rnd_arr[-(name_arr == 'Bob')] #输出的是 name_arr!='Bob'的行

[[ 0.4409493   1.48540013  0.40731781  0.16606016]
 [ 0.84783595 -2.15533993  1.50628519 -0.31510995]
 [ 0.15842983 -0.11273919  0.06812044 -0.24180305]
 [-1.73153848  0.32802232 -0.28211856 -0.22661218]
 [-0.00328644 -0.15188049  0.92744076 -1.04438799]]


e:\programs\anaconda\lib\site-packages\ipykernel\__main__.py:1: DeprecationWarning: numpy boolean negative (the unary `-` operator) is deprecated, use the bitwise_xor (the `^` operator) or the logical_xor function instead.
  if __name__ == '__main__':


In [27]:
print rnd_arr[name_arr != 'Bob']
mask_arr = (name_arr == 'Bob')| (name_arr == 'Will')
print rnd_arr[mask_arr]
print name_arr
rnd_arr[name_arr == 'Joe'] = 7
print rnd_arr

[[ 0.4409493   1.48540013  0.40731781  0.16606016]
 [ 0.84783595 -2.15533993  1.50628519 -0.31510995]
 [ 0.15842983 -0.11273919  0.06812044 -0.24180305]
 [-1.73153848  0.32802232 -0.28211856 -0.22661218]
 [-0.00328644 -0.15188049  0.92744076 -1.04438799]]
[[-1.42800631 -2.62500425 -1.52057421 -1.3482058 ]
 [ 0.84783595 -2.15533993  1.50628519 -0.31510995]
 [-1.59846491 -1.47390465 -0.13706371 -2.51937338]
 [ 0.15842983 -0.11273919  0.06812044 -0.24180305]]
['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[-1.42800631 -2.62500425 -1.52057421 -1.3482058 ]
 [ 7.          7.          7.          7.        ]
 [ 0.84783595 -2.15533993  1.50628519 -0.31510995]
 [-1.59846491 -1.47390465 -0.13706371 -2.51937338]
 [ 0.15842983 -0.11273919  0.06812044 -0.24180305]
 [ 7.          7.          7.          7.        ]
 [ 7.          7.          7.          7.        ]]
