In [1]:
import numpy as np

In [3]:
print 'Fancy Indexing: 使用整数数组作为索引'
arr =  np.empty((8, 4))
for i in range(8):
    arr[i] = i
print arr    

Fancy Indexing: 使用整数数组作为索引
[[ 0.  0.  0.  0.]
 [ 1.  1.  1.  1.]
 [ 2.  2.  2.  2.]
 [ 3.  3.  3.  3.]
 [ 4.  4.  4.  4.]
 [ 5.  5.  5.  5.]
 [ 6.  6.  6.  6.]
 [ 7.  7.  7.  7.]]


In [5]:
#指定第一维
print arr[[4,3,0,6]]
print arr[[-3,-5,-7]]

[[ 4.  4.  4.  4.]
 [ 3.  3.  3.  3.]
 [ 0.  0.  0.  0.]
 [ 6.  6.  6.  6.]]
[[ 5.  5.  5.  5.]
 [ 3.  3.  3.  3.]
 [ 1.  1.  1.  1.]]


In [10]:
arr = np.arange(32).reshape((8, 4))
print arr
print arr[[1, 5, 7, 2], [0, 3, 1, 2]] #指定前两维

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[ 4 23 29 10]


In [12]:
print arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]
print arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [13]:
np.ix_?