In [1]:
import numpy as np
import numpy.random as np_random

In [2]:
print '转置矩阵'
arr = np.arange(15).reshape((3, 5))
print arr
print arr.T

转置矩阵
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [3]:
print '转置矩阵做点积'
arr= np_random.randn(6, 3)
print np.dot(arr.T, arr)

转置矩阵做点积
[[ 5.7096878   2.41366263  1.88994973]
 [ 2.41366263  7.9364555  -4.15577044]
 [ 1.88994973 -4.15577044  8.2566673 ]]


In [4]:
print '高维矩阵转换'
arr = np.arange(16).reshape((2, 2, 4))
print arr

高维矩阵转换
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [6]:
print arr.transpose((1, 0, 2))
print arr.swapaxes(1, 2)

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]
[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


In [7]:
arr2 = np.array([['xiaozhang','xiaowang'],['30','40'],['engineer','teacher']])
print arr2.swapaxes(0,1)

[['xiaozhang' '30' 'engineer']
 ['xiaowang' '40' 'teacher']]
