In [29]:
import numpy as np
import numpy.random as np_random

In [30]:
print '求平方根'
arr = np.arange(10)
print np.sqrt(arr)

求平方根
[ 0.          1.          1.41421356  1.73205081  2.          2.23606798
  2.44948974  2.64575131  2.82842712  3.        ]


In [31]:
print '数组比较'
x = np_random.randn(8)
y = np_random.randn(8)
print x
print y
print np.maximum(x,y)

数组比较
[ 0.7545063   1.09322751 -0.61806054 -1.01449904 -1.03062829 -0.43887283
  0.18096014  0.2158842 ]
[-0.29827664 -0.4190177  -0.24344043  1.02676912 -0.41224523  0.76204459
 -0.36508918  0.79134304]
[ 0.7545063   1.09322751 -0.24344043  1.02676912 -0.41224523  0.76204459
  0.18096014  0.79134304]


In [32]:
print '四舍五入到接近的整数'
arr = np.array([1, 2.4, 3.1, 5.6])
print np.rint(arr)
print '整数 小数分开存为两个数组'
print np.modf(arr)

四舍五入到接近的整数
[ 1.  2.  3.  6.]
整数 小数分开存为两个数组
(array([ 0. ,  0.4,  0.1,  0.6]), array([ 1.,  2.,  3.,  5.]))


In [33]:
print '分为表示关于判断NaN（非数字）的逻辑数组'
arr = np.array(['1','f', '3', '42', 'd'])
print np.dtype
# todo 
np.isnan(np.nan)
np.isnan(np.inf)
np.isnan([np.log(-1.),1.,np.log(0)])

分为表示关于判断NaN（非数字）的逻辑数组
<type 'numpy.dtype'>


e:\programs\anaconda\lib\site-packages\ipykernel\__main__.py:7: RuntimeWarning: invalid value encountered in log
e:\programs\anaconda\lib\site-packages\ipykernel\__main__.py:7: RuntimeWarning: divide by zero encountered in log


array([ True, False, False], dtype=bool)

In [34]:
print np.isfinite(np.inf)
print np.isinf(np.inf)

False
True


In [35]:
print '三角函数'
arr = np.arange(10).reshape(2,5)
print np.cos(arr)

三角函数
[[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362]
 [ 0.28366219  0.96017029  0.75390225 -0.14550003 -0.91113026]]


In [36]:
print '逻辑取反 与 取反'
print np.logical_not(arr)
print -arr

逻辑取反 与 取反
[[ True False False False False]
 [False False False False False]]
[[ 0 -1 -2 -3 -4]
 [-5 -6 -7 -8 -9]]


In [37]:
print '二元函数'
arr1 = [ 1, 3, 4, 14, 62]
arr2 = [2, 5, 65, 7, 2]
print np.add(arr1,arr2)
print np.subtract(arr1,arr2)
print np.multiply(arr1,arr2)
print np.divide(arr1,arr2)
print '向下取整除法'
print np,floor_divede(arr1, arr2)

二元函数
[ 3  8 69 21 64]
[ -1  -2 -61   7  60]
[  2  15 260  98 124]
[ 0  0  0  2 31]
向下取整除法
<module 'numpy' from 'e:\programs\anaconda\lib\site-packages\numpy\__init__.pyc'>

NameError: name 'floor_divede' is not defined

In [38]:
print power(arr1,arr2) #a^b
print maximum(arr1,arr2) #fmax(arr1,arr2)会忽略NaN
print minimum(arr1,arr2) #fmin(arr1,arr2)会忽略NaN
print mod(arr1,arr2)

NameError: name 'power' is not defined

In [ ]:
#todo